### ISSUE TITLE
Config example shows HTTPS repo URL but code expects local path

### ISSUE THREAD

**Issue by adam-nebulaworks** [Nebulaworks/orion#8]
The code below uses the paths from my local systems and tries to run the tool in the Orion repo as an example. My local clone of that repo was in `/home/adam/local/internal/repo_clones/orion`.

To reproduce the error:
```
cp ./gen_release_sample.config ./.gen_release.config
$Env:CONFIG_LOC = "/home/adam/local/internal/repo_clones/orion/scripts/gen_release_notes/.gen_release.config"
$Env:GITHUB_TOKEN = "notatoken"
genreleasenotes RC/0.28 RC/0.29 main 32                                                                      
Traceback (most recent call last):
  File "/home/adam/opt/allvenv/bin/genreleasenotes", line 33, in <module>
    sys.exit(load_entry_point('gen-release-notes==1.0.0', 'console_scripts', 'genreleasenotes')())
  File "/home/adam/opt/allvenv/bin/generate.py", line 72, in main
    repo = Repo(repo_url)
  File "/home/adam/opt/allvenv/lib/python3.9/site-packages/git/repo/base.py", line 152, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /home/adam/local/internal/repo_clones/orion/scripts/gen_release_notes/https:/github.com/Nebulaworks/orion
```

To clear the error, change this line in `.gen_release.config`:
```
"repo_url": "https://github.com/Nebulaworks/orion",
```
To:
```
"repo_url": "/home/adam/local/internal/repo_clones/orion",
```

After that you'll get unrelated errors about branch names and such (the Orion repo isn't actually in a state where it's ready to generate release notes because no releases are pending).

The code creates a [GitPython](https://gitpython.readthedocs.io/en/3.1.24/index.html) [Repo object around this path](https://github.com/Nebulaworks/orion/blob/main/scripts/gen_release_notes/generate.py#L72). [That object's constructor expects a local path](https://gitpython.readthedocs.io/en/3.1.24/reference.html#git.repo.base.Repo.__init__).

**Comment by PhinnyG** [comment]
@adam-nebulaworks I was able to recreate the first issue, but after following your solution I ran into another issue. When I change "repo_url" to the path where my local clone is, I get a similar error as before.

`Traceback (most recent call last):
  File "/home/finnwhite/.local/bin/genreleasenotes", line 8, in <module>
    sys.exit(main())
  File "/home/finnwhite/.local/bin/generate.py", line 72, in main
    repo = Repo(repo_url)
  File "/home/finnwhite/.local/lib/python3.9/site-packages/git/repo/base.py", line 152, in __init__
    raise NoSuchPathError(epath)
git.exc.NoSuchPathError: /home/finnwhite/GitClones/orion/scripts/gen_release_notes/home/finnwhite/GitClones/orion
`
It is appending the "repo_url" path to the end of your current path. Which you can work around, but to me that seems like a strange effect. 

Did you change where you were running the script between the two cases (url vs local path)? because you can see the append effect in your first error message with the url.
